
import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime, date

st.set_page_config(page_title="Bryce Pokémon Ops", layout="wide")

st.title("Bryce Pokémon Ops 📈🃏")
st.caption("Upload your weekly Collectr export → get LIST NOW / HOLD / TREND ALERTS / GRADING CANDIDATES. Profit-per-hour + cashflow safety.")

with st.sidebar:
    st.header("Assumptions")
    pack_spend = st.number_input("Pack/Box spend to allocate ($)", min_value=0.0, value=1700.0, step=50.0)
    ebay_fee = st.number_input("eBay fee %", min_value=0.0, max_value=30.0, value=13.25, step=0.25) / 100.0
    fast_discount = st.number_input("Fast-sell discount % (vs market)", min_value=0.0, max_value=50.0, value=8.0, step=1.0) / 100.0

    st.subheader("Shipping + supplies (simple)")
    ship_pwe = st.number_input("PWE shipping+postage ($) (<= $20)", min_value=0.0, value=1.25, step=0.25)
    ship_tracked = st.number_input("Tracked shipping ($) (> $20)", min_value=0.0, value=4.50, step=0.50)
    supplies = st.number_input("Supplies per order ($)", min_value=0.0, value=0.30, step=0.05)
    min_profit = st.number_input("Min profit to list ($)", min_value=0.0, value=10.0, step=1.0)

    st.subheader("Grading (moderate)")
    grade_cost = st.number_input("Estimated grading cost per card ($)", min_value=0.0, value=22.0, step=1.0)
    grade_min_raw = st.number_input("Min raw price to consider grading ($)", min_value=0.0, value=25.0, step=5.0)
    grade_min_upside = st.number_input("Min expected upside to flag ($)", min_value=0.0, value=50.0, step=10.0)
    today = st.date_input("Snapshot date", value=date.today())

st.divider()

st.subheader("1) Upload your Collectr export (CSV)")
csv = st.file_uploader("Collectr export.csv", type=["csv"], key="collectr")

st.subheader("2) (Optional) Upload your history file to enable trend alerts")
hist = st.file_uploader("History file (CSV generated by this app)", type=["csv"], key="history")

def normalize_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    # common synonyms
    rename = {
        "Product": "Product Name",
        "Name": "Product Name",
        "Quantity": "Qty",
        "Average Cost Paid": "Avg Cost Paid",
        "Market Price": "Collectr Market Price",
        "Watchlist": "Collectr Watchlist",
    }
    for k,v in rename.items():
        if k in df.columns and v not in df.columns:
            df = df.rename(columns={k:v})
    return df

def safe_num(s):
    return pd.to_numeric(s, errors="coerce").fillna(0.0)

def build_id(df: pd.DataFrame) -> pd.Series:
    if "ItemKey" in df.columns:
        return df["ItemKey"].astype(str)
    parts = []
    for c in ["Product Name","Set","Card #","Variant","Rarity","Grade","Condition"]:
        if c in df.columns:
            parts.append(df[c].astype(str).fillna(""))
    if not parts:
        return pd.Series(range(len(df))).astype(str)
    return ("|".join(["{"])*0) or (parts[0].str.strip() + "|" + (parts[1].str.strip() if len(parts)>1 else ""))

def ebay_sold_link(name, set_name=None, card_no=None, variant=None, grade=None):
    q = str(name)
    for extra in [set_name, card_no, variant, grade]:
        if extra and str(extra).strip() and str(extra).strip() != "nan":
            q += " " + str(extra)
    q = q.replace(" ", "+")
    return f"https://www.ebay.com/sch/i.html?_nkw={q}&LH_Sold=1&LH_Complete=1"

def tcg_link(name, set_name=None, card_no=None):
    q = str(name)
    for extra in [set_name, card_no]:
        if extra and str(extra).strip() and str(extra).strip() != "nan":
            q += " " + str(extra)
    q = q.replace(" ", "+")
    return f"https://www.tcgplayer.com/search/pokemon/product?q={q}"

def compute(df: pd.DataFrame) -> pd.DataFrame:
    df = normalize_cols(df)

    # required-ish columns
    if "Qty" not in df.columns: df["Qty"] = 1
    if "Avg Cost Paid" not in df.columns: df["Avg Cost Paid"] = 0
    if "Collectr Market Price" not in df.columns: df["Collectr Market Price"] = 0
    if "Price Override" not in df.columns: df["Price Override"] = 0

    df["Qty"] = safe_num(df["Qty"])
    df["Avg Cost Paid"] = safe_num(df["Avg Cost Paid"])
    df["Collectr Market Price"] = safe_num(df["Collectr Market Price"])
    df["Price Override"] = safe_num(df["Price Override"])

    df["Effective Price"] = np.where(df["Price Override"] > 0, df["Price Override"], df["Collectr Market Price"])
    df["Market Value (Total)"] = df["Effective Price"] * df["Qty"]
    df["Cost Basis (Total)"] = df["Avg Cost Paid"] * df["Qty"]

    # allocation basis for zero-cost items
    df["Pack Cost Basis Value"] = np.where(df["Avg Cost Paid"] == 0, df["Market Value (Total)"], 0.0)
    total_basis = df["Pack Cost Basis Value"].sum()
    df["Allocated Pack Cost (Total)"] = np.where(
        (df["Avg Cost Paid"] == 0) & (total_basis > 0),
        (df["Pack Cost Basis Value"] / total_basis) * pack_spend,
        0.0
    )
    df["True Cost Basis (Total)"] = df["Cost Basis (Total)"] + df["Allocated Pack Cost (Total)"]

    # targets + ebay net
    df["Target Sell (Fast)"] = df["Effective Price"] * (1 - fast_discount)
    ship = np.where(df["Target Sell (Fast)"] <= 20, ship_pwe, ship_tracked)
    df["eBay Net/Unit (Fast)"] = (df["Target Sell (Fast)"] * (1 - ebay_fee)) - ship - supplies
    df["True eBay Profit (Total)"] = (df["eBay Net/Unit (Fast)"] * df["Qty"]) - df["True Cost Basis (Total)"]
    df["True eBay Margin %"] = np.where(
        (df["eBay Net/Unit (Fast)"] * df["Qty"]) > 0,
        df["True eBay Profit (Total)"] / (df["eBay Net/Unit (Fast)"] * df["Qty"]),
        0.0
    )

    # channel suggestion (simple)
    df["Suggested Channel"] = np.where(df["Target Sell (Fast)"] <= 20, "Online (PWE)", "Online (Tracked)")
    df["Suggested Action"] = np.where(df["True eBay Profit (Total)"] >= min_profit, "LIST NOW", "HOLD / BUNDLE")

    # links
    name = df["Product Name"] if "Product Name" in df.columns else pd.Series(["(missing name)"]*len(df))
    setn = df["Set"] if "Set" in df.columns else pd.Series([""]*len(df))
    cardno = df["Card #"] if "Card #" in df.columns else pd.Series([""]*len(df))
    variant = df["Variant"] if "Variant" in df.columns else pd.Series([""]*len(df))
    grade = df["Grade"] if "Grade" in df.columns else pd.Series([""]*len(df))

    df["eBay Sold Comps"] = [ebay_sold_link(n, s, c, v, g) for n,s,c,v,g in zip(name, setn, cardno, variant, grade)]
    df["TCGplayer Search"] = [tcg_link(n, s, c) for n,s,c in zip(name, setn, cardno)]

    # grading "take a look"
    # user will paste PSA comps later; for now we flag based on raw price tier + condition/grade hints.
    cond = df["Condition"].astype(str).str.lower() if "Condition" in df.columns else pd.Series([""]*len(df))
    looks_clean = ~cond.str.contains("hp|dam|dmg|played|crease|bend", na=False)
    df["Grade - Take a Look?"] = np.where((df["Effective Price"] >= grade_min_raw) & looks_clean, "TAKE A LOOK", "")

    return df

def kpi(a, b, c, d):
    col1, col2, col3, col4 = st.columns(4)
    col1.metric(a[0], a[1])
    col2.metric(b[0], b[1])
    col3.metric(c[0], c[1])
    col4.metric(d[0], d[1])

if csv is None:
    st.info("Upload your Collectr export to get your queues.")
    st.stop()

df_raw = pd.read_csv(csv)
df = compute(df_raw)

# KPIs
total_value = df["Market Value (Total)"].sum()
true_cost = df["True Cost Basis (Total)"].sum()
pl = total_value - true_cost
roi = (total_value / true_cost - 1) if true_cost > 0 else 0.0

kpi(
    ("Collection value", f"${total_value:,.0f}"),
    ("True cost basis", f"${true_cost:,.0f}"),
    ("Unrealized P/L", f"${pl:,.0f}"),
    ("Unrealized ROI", f"{roi*100:,.1f}%"),
)

st.divider()

# LIST NOW queue
st.header("🔴 LIST NOW queue (Top 20)")
list_now = df.sort_values("True eBay Profit (Total)", ascending=False).head(20).copy()
show_cols = [c for c in ["Product Name","Set","Card #","Variant","Grade","Qty","Target Sell (Fast)","True eBay Profit (Total)","True eBay Margin %","Suggested Channel","eBay Sold Comps","TCGplayer Search"] if c in list_now.columns]
st.dataframe(list_now[show_cols], use_container_width=True)

st.download_button("Download LIST NOW (CSV)", list_now.to_csv(index=False).encode("utf-8"), file_name="list_now.csv")

# HOLD queue
st.header("🟢 HOLD queue (strong value / low profit-per-hour)")
hold = df[df["Suggested Action"] != "LIST NOW"].sort_values("Market Value (Total)", ascending=False).head(30)
show_cols2 = [c for c in ["Product Name","Set","Card #","Variant","Grade","Qty","Market Value (Total)","Suggested Action","eBay Sold Comps"] if c in hold.columns]
st.dataframe(hold[show_cols2], use_container_width=True)
st.download_button("Download HOLD (CSV)", hold.to_csv(index=False).encode("utf-8"), file_name="hold_queue.csv")

# Grading take-a-look
st.header("🔵 TAKE A LOOK AT GRADING (moderate)")
grade_q = df[df["Grade - Take a Look?"] == "TAKE A LOOK"].sort_values("Effective Price", ascending=False).head(50)
show_cols3 = [c for c in ["Product Name","Set","Card #","Variant","Condition","Effective Price","Qty","eBay Sold Comps"] if c in grade_q.columns]
st.dataframe(grade_q[show_cols3], use_container_width=True)
st.download_button("Download Grading Take-a-Look (CSV)", grade_q.to_csv(index=False).encode("utf-8"), file_name="grading_take_a_look.csv")

st.divider()

# Trend tracking
st.header("🟣 Trend Alerts (requires history upload)")
df["SnapshotDate"] = pd.to_datetime(today)
df["ItemID"] = build_id(df)
snap = df[["SnapshotDate","ItemID"]].copy()
snap["Effective Price"] = df["Effective Price"].astype(float)
snap["Market Value (Total)"] = df["Market Value (Total)"].astype(float)

if hist is None:
    st.info("Upload your history CSV to enable trend alerts. After this run, download the updated history and use it next week.")
    history = snap.copy()
else:
    history = pd.read_csv(hist)
    history["SnapshotDate"] = pd.to_datetime(history["SnapshotDate"])
    # append new snapshot; de-dup per ItemID+date
    history = pd.concat([history, snap], ignore_index=True)
    history = history.drop_duplicates(subset=["SnapshotDate","ItemID"], keep="last")

# compute trend deltas (closest prior points)
latest_date = history["SnapshotDate"].max()
latest = history[history["SnapshotDate"] == latest_date].copy()

def pct_change_days(days: int):
    cutoff = latest_date - pd.Timedelta(days=days)
    prev = history[history["SnapshotDate"] <= cutoff].sort_values("SnapshotDate").groupby("ItemID").tail(1)
    merged = latest.merge(prev[["ItemID","Effective Price"]], on="ItemID", how="left", suffixes=("","_prev"))
    merged[f"chg_{days}d"] = np.where(merged["Effective Price_prev"].notna() & (merged["Effective Price_prev"]>0),
                                     (merged["Effective Price"]/merged["Effective Price_prev"])-1,
                                     np.nan)
    return merged[["ItemID", f"chg_{days}d"]]

c30 = pct_change_days(30)
c60 = pct_change_days(60)
c90 = pct_change_days(90)

alerts = latest.merge(c30, on="ItemID", how="left").merge(c60, on="ItemID", how="left").merge(c90, on="ItemID", how="left")

def classify(row):
    for days,thr,label in [(90,-0.35,"SELL NOW"), (60,-0.25,"LIST SOON"), (30,-0.15,"WATCH")]:
        val = row.get(f"chg_{days}d")
        if pd.notna(val) and val <= thr:
            return label
    # hype
    v30 = row.get("chg_30d")
    if pd.notna(v30) and v30 >= 0.30:
        return "SELL INTO HYPE"
    return ""

alerts["Trend Alert"] = alerts.apply(classify, axis=1)

# join back descriptive fields
desc_cols = [c for c in ["Product Name","Set","Card #","Variant","Grade","Qty","eBay Sold Comps"] if c in df.columns]
desc = df.copy()
desc["ItemID"] = build_id(df)
desc = desc[["ItemID"] + desc_cols].drop_duplicates("ItemID")

alerts = alerts.merge(desc, on="ItemID", how="left")
alerts = alerts[alerts["Trend Alert"]!=""].copy()

if len(alerts)==0:
    st.success("No trend alerts triggered (or not enough history yet).")
else:
    alerts = alerts.sort_values(["Trend Alert","Market Value (Total)"], ascending=[True,False])
    show_cols4 = [c for c in ["Trend Alert","Product Name","Set","Card #","Variant","Grade","Qty","Effective Price","chg_30d","chg_60d","chg_90d","eBay Sold Comps"] if c in alerts.columns]
    st.dataframe(alerts[show_cols4], use_container_width=True)

# history download
st.subheader("Download updated history (use this next week)")
st.download_button("Download history.csv", history.to_csv(index=False).encode("utf-8"), file_name="history.csv")

st.caption("Note: trend alerts improve after ~4–8 weeks of history. This app avoids brittle scraping; it links you directly to comps for quick verification.")
